project_name: 'UNetSR'
experiment_name: 'UNetSR2-0131' # TODO: may be updated

training:
  max_epochs: 10000
  validation_freq: 1000 # TODO: may be updated
  checkpoint_freq: 2000 # TODO: may be updated
  wandb_id: 'ikujyhr8' # TODO: may be updated

model:
  name: 'UNetSR'
  gpu: True
  is_data_parallel: False
  network:
    name: 'UNetSR2'
    img_channels: 1
    min: 0.0
    max: 1.0
    init: ['orthogonal', 0.2, 'uniform']
  optimizer:
    name: 'Adam'
    lr: 2e-4
    weight_decay: 1e-8
  scheduler:
    name: 'CosineAnnealingLR_Restart'  # ~ for no scheduler
    T_period: [12500, 12500, 12500, 12500]
    restarts: [12500, 25000, 37500]
    weights: [1, 1, 1]
    eta_min: 1e-7
  loss_function:
    name: 'MSE'  # ~ for no loss_function
  checkpoint:
    network: ~
    training_state: ~

train_data:
  name: 'HrLrKernelFromBioSR'
  is_train: True
  preload_data: ~
  gpu_id: ~
  repeat: ~ # TODO: may be updated
  img_filter:
    img_root: '../BioDataset/Mixed'
    structure_selected: [1, 2, 3, 4]
    included_idx: [11, 100]
  hr_crop:
    mode: 'random' # TODO: may be updated
    center_pos: [-1, -1]
    scan_shape: [-1, -1]
    hr_size: [128, 128] # TODO: may be updated
  scale: 2 # TODO: may be updated
  img_signal: [100, 1000]
  psf_settings:
      kernel_size: 33
      NA: 1.35
      Lambda: 0.525
      RefractiveIndex: 1.33
      SigmaX: 2.0
      SigmaY: 2.0
      Pixelsize: 0.0313
      nMed: 1.33
      phaseZ:
          idx_start: 4
          num_idx: 15
          mode: 'gaussian'
          std: 0.125
          bound: 1.0
  sup_phaseZ: 'all'  # all | [begin, end]
  padding:
      mode: 'circular'  # constant | reflect | replicate | circular
      value: -1  # for constant mode
  loader_settings:
    batch_size: 32 # TODO: may be updated
    shuffle: True
    num_workers: 4
    pin_memory: False
    drop_last: True

test_data:
  name: 'HrLrKernelFromBioSR'
  is_train: False
  preload_data: # './data/test_loaders/zernike-40item.mat' # TODO: may be updated
  gpu_id: ~
  repeat: ~ # TODO: may be updated
  img_filter:
    img_root: '../BioDataset/Mixed'
    structure_selected: [1, 2, 3, 4]
    included_idx: [1, 10]
  hr_crop:
    mode: 'random' # TODO: may be updated
    center_pos: [-1, -1]
    scan_shape: [-1, -1]
    hr_size: [128, 128] # TODO: may be updated
  scale: 2 # TODO: may be updated
  img_signal: [1000]
  psf_settings:
      kernel_size: 33
      NA: 1.35
      Lambda: 0.525
      RefractiveIndex: 1.33
      SigmaX: 2.0
      SigmaY: 2.0
      Pixelsize: 0.0313
      nMed: 1.33
      phaseZ:
          idx_start: 4
          num_idx: 15
          mode: 'gaussian'
          std: 0.125
          bound: 1.0
  sup_phaseZ: 'all'  # all | [begin, end]
  padding:
      mode: 'circular'  # constant | reflect | replicate | circular
      value: -1  # for constant mode
  loader_settings:
    batch_size: 1
    shuffle: False
    num_workers: 0
    pin_memory: False
    drop_last: False
