project_name: 'SFTDFCAN'
experiment_name: 'SFTDFCAN-1216-exp-coma-CCPs' # TODO: may be updated

training:
  max_epochs: 100000
  validation_freq: 4000 # TODO: may be updated
  checkpoint_freq: 8000 # TODO: may be updated
  wandb_id: 'sdfbh234ysdh' # TODO: may be updated

model:
  name: 'SFTDFCAN'
  gpu: True
  is_data_parallel: False
  pca_mean: './data/pca_matrices_zernike/pca_mean.pth'
  pca_matrix: './data/pca_matrices_zernike/pca_matrix65.pth'
  norm_lr: False
  norm_hr: False
  network:
    name: 'SFTDFCAN'
    in_nc: 1
    out_nc: 1
    nf: 64
    nb: 16
    scale: 2
    input_para: 65
    min: 0.0
    max: 1.0
    init: ['orthogonal', 0.2, 'uniform'] # ~ for no init
  optimizer:
    name: 'Adam'  # ~ for no optimizer
    lr: 1e-4
    weight_decay: 0.0
  scheduler:
    name: 'ReduceLROnPlateau'  # ~ for no scheduler
    factor: 0.5
    patience: 2
    min_lr: 1e-4
    step_interval: 2000
    T_period: [20000, 20000, 20000, 20000]
    restarts: [20000, 40000, 60000]
    weights: [1, 1, 1]
    eta_min: 1e-7
  loss_function:
    name: 'L1'  # ~ for no loss_function
  checkpoint:
    network: './experiments/SFTDFCAN-0829-same-depth/900000_network.pth'
    training_state: './experiments/SFTDFCAN-0829-same-depth/900000_training_state.pth'

train_data:
  name: 'HrLrKernelFromBioSR'
  is_train: True
  preload_data: ~
  gpu_id: ~
  repeat: ~
  img_filter:
    img_root: './BioDataset/Mixed'
    structure_selected: [1] #1 CCPs 2 ER 3 MTs  TODO: may be updated
    included_idx: [11, 100]
  hr_crop:
    mode: 'random'
    center_pos: [-1, -1]
    scan_shape: [-1, -1]
    hr_size: [128, 128]
  scale: 2
  img_signal: [120, 400]
  psf_settings:
    type: 'Zernike' # Gaussian | Zernike
    kernel_size: 33

    sigma: 2.6
    sigma_min: 0.2
    sigma_max: 4.0
    prob_isotropic: 0.0
    scale: 2

    NA: 1.35
    Lambda: 0.525
    RefractiveIndex: 1.33
    SigmaX: 2.0
    SigmaY: 2.0
    Pixelsize: 0.0313
    nMed: 1.33
    phaseZ:
      idx_start: [3,6]
      num_idx: [1,2]
      mode: 'uniform'
      std: 0.125
      bound: [0.1, 0.4]
  sup_phaseZ: 'all'  # all | [begin, end]
  padding:
    mode: 'circular'  # constant | reflect | replicate | circular
    value: -1  # for constant mode
  loader_settings:
    batch_size: 8
    shuffle: True
    num_workers: 4
    pin_memory: False
    drop_last: True

test_data:
  name: 'HrLrKernelFromBioSR'
  is_train: False
  preload_data: # './data/test_loaders/zernike-40item.mat'
  gpu_id: ~
  repeat: 3 #
  img_filter:
    img_root: './BioDataset/Mixed'
    structure_selected: [1] # 1 CCPs 2 ER 3 MTs TODO: may be updated
    included_idx: [1, 10]
  hr_crop:
    mode: 'random'
    center_pos: [-1, -1]
    scan_shape: [-1, -1]
    hr_size: [128, 128]
  scale: 2
  img_signal: [120,400]
  psf_settings:
    type: 'Zernike' # Gaussian | Zernike
    kernel_size: 33

    sigma: 2.6
    sigma_min: 0.2
    sigma_max: 4.0
    prob_isotropic: 0.0
    scale: 2

    NA: 1.35
    Lambda: 0.525
    RefractiveIndex: 1.33
    SigmaX: 2.0
    SigmaY: 2.0
    Pixelsize: 0.0313
    nMed: 1.33
    phaseZ:
      idx_start: [3,6]
      num_idx: [1,2]
      mode: 'uniform'
      std: 0.125
      bound: [0.1, 0.4]
  sup_phaseZ: 'all'  # all | [begin, end]
  padding:
    mode: 'circular'  # constant | reflect | replicate | circular
    value: -1  # for constant mode
  loader_settings:
    batch_size: 1
    shuffle: False
    num_workers: 0
    pin_memory: False
    drop_last: False
