project_name: 'FFTRCANResUNet'
experiment_name: 'FFTRCANResUNet-1216-exp-coma' # TODO: may be updated

training:
  max_epochs: 100000
  validation_freq: 2000 # TODO: may be updated
  checkpoint_freq: 10000 # TODO: may be updated
  wandb_id: 'asdf2wfbhhf' # TODO: may be updated

model:
  name: 'UNetBased'
  gpu: True
  is_data_parallel: False
  norm_lr: True
  norm_k: True
  network:
    name: 'FFTRCANResUNet'
    fft: True
    fft_shift: False
    fft_forward: False
    fft_brunch: True
    in_channels: 1
    encoder_channels: 128
    num_features: 64
    num_rg: 2
    num_rcab: 4
    reduction: 16
    num_down_up: 5
    num_pixel_stack_layer: 2
    out_channels: 1
    init: ~
  optimizer:
    name: 'Adam'
    lr: 8e-5
    weight_decay: 1e-8
  scheduler:
    name: 'ReduceLROnPlateau'
    factor: 0.5
    patience: 2
    min_lr: 1e-4
    step_interval: 2000
  loss_function:
    name: 'MSE'
  checkpoint:
    network: ~
    training_state: ~

train_data:
  name: 'HrLrKernelFromBioSR'
  is_train: True
  preload_data: ~
  gpu_id: ~
  repeat: ~
  img_filter:
    img_root: './BioDataset/Mixed'
    structure_selected: [1, 2, 3]
    included_idx: [11, 100]
  hr_crop:
    mode: 'random'
    center_pos: [-1, -1]
    scan_shape: [-1, -1]
    hr_size: [264, 264] #
  scale: 2  #
  img_signal: [120, 400]
  psf_settings:
      type: 'Zernike' # Gaussian | Zernike

      kernel_size: 33

      sigma: 2.6
      sigma_min: 0.2
      sigma_max: 4.0
      prob_isotropic: 0.0
      scale: 2

      NA: 1.35
      Lambda: 0.525
      RefractiveIndex: 1.33
      SigmaX: 2.0
      SigmaY: 2.0
      Pixelsize: 0.0313
      nMed: 1.33
      phaseZ:
        idx_start: [3,6]
        num_idx: [1,2]
        mode: 'uniform'
        std: 0.125
        bound: [0.1, 0.4]
  sup_phaseZ: 'all'  # all | [begin, end]
  padding:
      mode: 'circular'  # constant | reflect | replicate | circular
      value: -1  # for constant mode
  loader_settings:
    batch_size: 4
    shuffle: True
    num_workers: 4
    pin_memory: False
    drop_last: True

test_data:
  name: 'HrLrKernelFromBioSR'
  is_train: False
  preload_data: # './data/test_loaders/zernike-40item.mat'
  gpu_id: ~
  repeat: ~
  img_filter:
    img_root: './BioDataset/Mixed'
    structure_selected: [1, 2, 3]
    included_idx: [1, 10]
  hr_crop:
    mode: 'random'
    center_pos: [-1, -1]
    scan_shape: [-1, -1]
    hr_size: [264, 264]
  scale: 2
  img_signal: [120, 400]
  psf_settings:
      type: 'Zernike' # Gaussian | Zernike

      kernel_size: 33

      sigma: 2.6
      sigma_min: 0.2
      sigma_max: 4.0
      prob_isotropic: 0.0
      scale: 2

      NA: 1.35
      Lambda: 0.525
      RefractiveIndex: 1.33
      SigmaX: 2.0
      SigmaY: 2.0
      Pixelsize: 0.0313
      nMed: 1.33
      phaseZ:
        idx_start: [3,6]
        num_idx: [1,2]
        mode: 'uniform'
        std: 0.125
        bound: [0.1, 0.4]
  sup_phaseZ: 'all'  # all | [begin, end]
  padding:
      mode: 'circular'  # constant | reflect | replicate | circular
      value: -1  # for constant mode
  loader_settings:
    batch_size: 1
    shuffle: False
    num_workers: 0
    pin_memory: False
    drop_last: False
